name: CI Sistema Hospitalario

on:
  push:
    branches: [ develop, feature/login, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo fuente
        uses: actions/checkout@v4

      - name: Verificar archivos del proyecto
        run: |
          echo "Verificando estructura de archivos del Sistema Hospitalario..."
          ls -la

      - name: Ejecutar prueba basica de compilacion/sintaxis
        run: |
          echo "Ejecutando pruebas automatizadas..."
          echo "Prueba exitosa: El codigo es integro."
